export enum fetchFilesActionTypes {
  FETCH_FILES_REQUEST = "FETCH_FILES_REQUEST",
  FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS",
  FETCH_FILES_FAILURE = "FETCH_FILES_FAILURE",
}

export enum loginUserActionTypes {
  LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE",
  LOGOUT_USER = "LOGOUT_USER",
}

export enum registerUserActionTypes {
  REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE",
}
