name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.DEPLOYMENT_API}}
          heroku_app_name: "codingpilloweditor"
          heroku_email: "iamsomraj@gmail.com"
