name: Client-Unit-Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix client

      - name: Run test command
        run: npm run test --prefix client
